/**
 * Reads the mobility assets manifest (generated by scripts/rename-mobility-media.mjs).
 * Used by mobility detail pages to resolve /mobilities/{slug}/{type}/{filename}.
 */
import fs from 'fs';
import path from 'path';

export type MobilityManifest = Record<
  string,
  { images: string[]; videos: string[]; pdfs: string[]; ppts: string[] }
>;

function getManifestPath(): string {
  return path.join(process.cwd(), 'public', 'mobilities', 'manifest.json');
}

export function getMobilityManifest(): MobilityManifest {
  const manifestPath = getManifestPath();
  if (!fs.existsSync(manifestPath)) {
    return {};
  }
  const raw = fs.readFileSync(manifestPath, 'utf8');
  return JSON.parse(raw) as MobilityManifest;
}

export function getMobilityAssets(slug: string): {
  images: string[];
  videos: string[];
  pdfs: string[];
  ppts: string[];
} {
  const manifest = getMobilityManifest();
  const entry = manifest[slug] ?? {
    images: [],
    videos: [],
    pdfs: [],
    ppts: [],
  };
  return entry;
}

/** Base URL for mobility assets (e.g. /mobilities/kickoff-macedonia) */
export function getMobilityAssetBase(slug: string): string {
  return `/mobilities/${slug}`;
}
